In [1]:
from dummy_spatialdata import generate_dataset, generate_imagemodel, generate_labelmodel, generate_shapemodel, generate_tablemodel, generate_transformations
from dummy_spatialdata.generate_transformations import get_coordsystem_shape, get_coordsystem_transformations
from spatialdata.models import Image2DModel, ShapesModel, TableModel
import dummy_anndata
import spatialdata_plot as sdp 
import spatialdata as sd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import anndata as ad
import pdb

/Users/amanuky/miniforge3/envs/dummy_sd_env/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
generate_transformations({'trans_0': ['affine']})
generate_transformations({'trans_0': ['translation']})
generate_transformations({'trans_0': ['scale'], 'trans_1': ['scale']})
generate_transformations({'trans_1': ['affine', 'translation', 'scale']})

{'trans_1': Sequence 
     Affine (x, y -> x, y)
         [0.5 0.2 0. ]
         [0.1 0.5 0. ]
         [0. 0. 1.]
     Translation (x, y)
         [10. 20.]
     Scale (x, y)
         [0.5 0.5]}

In [ ]:
coordinate_systems = {
    'global': {'transformations': ['affine'], 'shape': {'x': 1000, 'y': 1000}},
    'global2': {'transformations': ['scale', 'translation'], 'shape':{'x': 1000, 'y': 1000}}
}
        
# get transformations of coordinate systems
get_coordsystem_transformations(coordinate_systems)

# get shapes of coordinate systems
get_coordsystem_shape(coordinate_systems, 'global')

{'global': {'transformations': ['affine'], 'shape': {'x': 1000, 'y': 1000}}, 'global2': {'transformations': ['scale', 'translation'], 'shape': {'x': 1000, 'y': 1000}}}
{'transformations': ['affine'], 'shape': {'x': 1000, 'y': 1000}}


{'x': 1000, 'y': 1000}

In [ ]:
coordinate_systems = {'trans_0': ['affine']}
transformations = {}
for i in coordinate_systems.keys():
    transformations.update(generate_transformations({i: coordinate_systems[i]}))
generate_imagemodel({'type': 'rgb', 'scale_factors': [2,2,2], 'shape': {'x': 1000, 'y': 1000}, 'transformations': 'trans_0'}, 'image_0', transformations = transformations)

trans_0
{'trans_0': Affine (x, y -> x, y)
    [0.5 0.2 0. ]
    [0.1 0.5 0. ]
    [0. 0. 1.]}
{'trans_0': Affine (x, y -> x, y)
    [0.5 0.2 0. ]
    [0.1 0.5 0. ]
    [0. 0. 1.]}


<xarray.DataTree>
Group: /
├── Group: /scale0
│       Dimensions:  (c: 3, y: 1000, x: 1000)
│       Coordinates:
│         * c        (c) int64 24B 0 1 2
│         * y        (y) float64 8kB 0.5 1.5 2.5 3.5 4.5 ... 996.5 997.5 998.5 999.5
│         * x        (x) float64 8kB 0.5 1.5 2.5 3.5 4.5 ... 996.5 997.5 998.5 999.5
│       Data variables:
│           image    (c, y, x) uint8 3MB dask.array<chunksize=(3, 256, 256), meta=np.ndarray>
├── Group: /scale1
│       Dimensions:  (c: 3, y: 500, x: 500)
│       Coordinates:
│         * c        (c) int64 24B 0 1 2
│         * y        (y) float64 4kB 1.0 3.0 5.0 7.0 9.0 ... 993.0 995.0 997.0 999.0
│         * x        (x) float64 4kB 1.0 3.0 5.0 7.0 9.0 ... 993.0 995.0 997.0 999.0
│       Data variables:
│           image    (c, y, x) uint8 750kB dask.array<chunksize=(3, 256, 256), meta=np.ndarray>
├── Group: /scale2
│       Dimensions:  (c: 3, y: 250, x: 250)
│       Coordinates:
│         * c        (c) int64 24B 0 1 2
│         * y        (y) float64 2kB 2.0 6.0 10.0 14.0 18.0 ... 986.0 990.0 994.0 998.0
│         * x        (x) float64 2kB 2.0 6.0 10.0 14.0 18.0 ... 986.0 990.0 994.0 998.0
│       Data variables:
│           image    (c, y, x) uint8 188kB dask.array<chunksize=(3, 250, 250), meta=np.ndarray>
└── Group: /scale3
        Dimensions:  (c: 3, y: 125, x: 125)
        Coordinates:
          * c        (c) int64 24B 0 1 2
          * y        (y) float64 1kB 4.0 12.0 20.0 28.0 36.0 ... 972.0 980.0 988.0 996.0
          * x        (x) float64 1kB 4.0 12.0 20.0 28.0 36.0 ... 972.0 980.0 988.0 996.0
        Data variables:
            image    (c, y, x) uint8 47kB dask.array<chunksize=(3, 125, 125), meta=np.ndarray>